# To use the default pimple 'DiC', use Controller::Action. To use Auryn recursive autowiring DiC, use Controller:Action
routes:
  home:
    pattern:  /
    defaults: { _controller: 'HomeController:indexAction' }
  login:
    pattern:  /login
    defaults: { _controller: 'HomeController:loginAction' }
  test:
    pattern:  /test
    defaults: {_controller:  'TestController:indexAction' }

  # Article RESTful resource (Index + CRUD)
  articles:
    pattern:  /api/articles
    defaults: { _controller: 'ArticleController:indexAction' }
  articles_create:
    pattern:  /api/articles
    defaults: { _controller: 'ArticleController:createAction' }
    method:   'POST'
  articles_retrieve:
    pattern:  /api/articles/{id}
    defaults: { _controller: 'ArticleController:retrieveAction' }
  articles_update:
    pattern:  /api/articles/{id}
    defaults: { _controller: 'ArticleController:updateAction' }
    method:   'PUT'
  articles_delete:
    pattern:  /api/articles/{id}
    defaults: { _controller: 'ArticleController:deleteAction' }
    method:   'DELETE'

  auth_sign_in:
    pattern:  /auth/sign_in
    defaults: { _controller: 'AuthController:signInAction' }
    method:   'POST'
  auth_get_api_key:
    pattern:  /auth/get_api_key
    defaults: { _controller: 'AuthController:getApiKeyAction' }
    method:   'POST'
