# To use the default pimple 'DiC', use Controller::Action. To use Auryn recursive autowiring DiC, use Controller:Action
routes:
  home:
    pattern:  /
    defaults: { _controller: 'HomeController:indexAction' }
  login:
    pattern:  /login
    defaults: { _controller: 'HomeController:loginAction' }
  test:
    pattern:  /test
    defaults: {_controller:  'TestController:indexAction' }

  # Article RESTful resource (Index + CRUD)
  articles:
    pattern:  /articles
    defaults: { _controller: 'ArticleController:indexAction' }
  articles_create:
    pattern:  /articles
    defaults: { _controller: 'ArticleController:createAction' }
    method:   'POST'
  articles_retrieve:
    pattern:  /articles/{id}
    defaults: { _controller: 'ArticleController:retrieveAction' }
  articles_update:
    pattern:  /articles/{id}
    defaults: { _controller: 'ArticleController:updateAction' }
    method:   'PUT'
  articles_delete:
    pattern:  /articles/{id}
    defaults: { _controller: 'ArticleController:deleteAction' }
    method:   'DELETE'
