security:
  firewalls:
    default:
      pattern:   ^((?!api).)*$
      anonymous: true
      form:
        login_path: /login
        check_path: /login_check
        default_target_path: /index.html
        always_use_default_target_path': true
      logout:
        logout_path:        /logout
        invalidate_session: false
    api_secured:
      pattern:    ^/api/articles
      api_key:    true
      stateless:  true
    # secured_area:
    #   pattern: ^/articles
    #   stateless: true
    #   simple_preauth:
    #     authenticator: apikey_authenticator
  heirarchy: 
    - [ 'ROLE_ADMIN', 'ROLE_USER' ]
  access_rules:
    - [ '^/login$', 'IS_AUTHENTICATED_ANONYMOUSLY' ]
    - [ '^/auth', 'IS_AUTHENTICATED_ANONYMOUSLY' ]
    # - [ '^/articles', 'IS_AUTHENTICATED_ANONYMOUSLY' ]
    - [ '^/.+$', 'ROLE_USER' ]
